MIN_PLAYERS_NUMBER = 2
MAX_PLAYERS_NUMBER = 6
DICE_MIN = 1
DICE_MAX = 6
DICE_AMOUNT = 2

BOARD = (('GO',),
         ('Property', 'Mediterranean Avenue', 'Purple', 60),
         ('Community Chest',),
         ('Property', 'Baltic Avenue', 'Purple', 60),
         ('Tax', 'Income tax', 200),
         ('Property', 'Reading Railroad', 'Railroad', 200),
         ('Property', 'Oriental Avenue', 'Light blue', 100),
         ('Chance',),
         ('Property', 'Vermont Avenue', 'Light blue', 100),
         ('Property', 'Connecticut Avenue', 'Light blue', 120),
         ('Jail',),
         ('Property', 'St Charles Place', 'Pink', 140),
         ('Property', 'Electric Company', 'Utility', 150),
         ('Property', 'States Avenue', 'Pink', 140),
         ('Property', 'Virginia Avenue', 'Pink', 160),
         ('Property', 'Pennsylvania Railroad', 'Railroad', 200),
         ('Property', 'St James Place', 'Orange', 180),
         ('Community Chest',),
         ('Property', 'Tennessee Avenue', 'Orange', 180),
         ('Property', 'New York Avenue', 'Orange', 200),
         ('Free Parking',),
         ('Property', 'Kentucky Avenue', 'Red', 220),
         ('Chance',),
         ('Property', 'Indiana Avenue', 'Red', 220),
         ('Property', 'Illinois Avenue', 'Red', 240),
         ('Property', 'B & O Railroad', 'Railroad', 200),
         ('Property', 'Atlantic Avenue', 'Yellow', 260),
         ('Property', 'Ventnor Avenue', 'Yellow', 260),
         ('Property', 'Water Works', 'Utility', 150),
         ('Property', 'Marvin Gardens', 'Yellow', 280),
         ('Go to jail',),
         ('Property', 'Pacific Avenue', 'Green', 300),
         ('Property', 'North Carolina Avenue', 'Green', 300),
         ('Community Chest',),
         ('Property', 'Pennsylvania Avenue', 'Green', 320),
         ('Property', 'Short Line Railroad', 'Railroad', 200),
         ('Chance',),
         ('Property', 'Park Place', 'Blue', 350),
         ('Tax', 'Luxury tax', 75),
         ('Property', 'Boardwalk', 'Blue', 400),
         )
